# Generated by Django 4.2.3 on 2023-07-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='titulo',
            field=models.CharField(max_length=40, verbose_name='titulo'),
        ),
    ]
