# Generated by Django 4.2.3 on 2023-07-23 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letras', '0002_alter_musica_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='musicas',
        ),
        migrations.AddField(
            model_name='musica',
            name='artista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='letras.artista'),
        ),
    ]
