# Generated by Django 4.2.3 on 2023-07-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letras', '0003_remove_artista_musicas_musica_artista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='letra',
            field=models.TextField(max_length=3000, verbose_name='letra'),
        ),
    ]
